### ISSUE TITLE
Modernizr didn't work

### ISSUE THREAD

**Issue by MoOx** [sams/Thematic-html5boilerplate#17]
I dont know why, but recently (I'm working on my website with this theme), modernizr inclusion is having some problem with the build version. It's seems that the option is not recorded into the wp options database. So the output is like this :

<script src="/wp-content/themes/moox/library/js/libs/modernizr-"></script>

I've install and uninstall theme, and modify options, it did work well :(

**Comment by sams** [comment]
Have you got this in header-extensions.php - from John Raz's fix?

`echo "\n<script src=\"".get_stylesheet_directory_uri()."/library/js/libs/$modernizr\"></script>\n";`

https://github.com/sams/Thematic-html5boilerplate/blob/master/library/extensions/header-extensions.php#L513

**Comment by MoOx** [comment]
Yep. The output give me that :
`<script src="http://moox.local/wp-content/themes/moox/library/js/libs/"></script>`
Seems the option is uninitialized

**Comment by sams** [comment]
do you have a selection list of modernizr builds?

commit 4924862 - adds modernizr 2 with yepnope js
I guess in somecases the option that sets the build of modernizr maybe unset if you have theme installed and pull updates - really it should default to 1.7

**Comment by MoOx** [comment]
It's okay with an update of the latest
